Repository zalando/connexion, pull requests merged in 2018-11, with the labels that each got.

#771 update documentation
  README.rst
  docs/cookbook.rst
  docs/index.rst
  docs/quickstart.rst
  docs/request.rst
  docs/routing.rst
Labels: documentation

#778 `collectionFormat` doesn't need the `'`
  docs/request.rst
Labels: ready

#726 simplify Operation class construction
  connexion/apis/abstract.py
  connexion/operations/__init__.py
  connexion/operations/abstract.py
  connexion/operations/openapi.py
  connexion/operations/swagger2.py
  connexion/spec.py
  tests/test_api.py
Labels: ready

#790 Run travis on python 3.7
  .travis.yml
  setup.py
  tox.ini
Labels: ready

#800 fix cli --stub
  connexion/handlers.py
  tests/fixtures/module_does_not_exist/openapi.yaml
  tests/fixtures/module_does_not_exist/swagger.yaml
Labels: ready

#738 Change can_read_body to body_exists in AioHttpApi.get_request
  connexion/apis/aiohttp_api.py
Labels: ready

#789 Fix handling additionalProperties in body
  connexion/operations/openapi.py
  tests/api/test_parameters.py
  tests/fakeapi/hello.py
  tests/fixtures/simple/openapi.yaml
  tests/fixtures/simple/swagger.yaml
Labels: bug
