Repository zalando/connexion, pull requests merged in 2019-12, with the labels that each got.

#1008 Do not sanitize body keys in OpenAPI 3
  connexion/operations/openapi.py
  tests/api/test_parameters.py
  tests/conftest.py
  tests/fakeapi/hello.py
  tests/fixtures/query_sanitazion/openapi.yaml
  tests/fixtures/query_sanitazion/swagger.yaml
  tests/fixtures/simple/openapi.yaml
  tests/fixtures/simple/swagger.yaml
Labels: ready

#851 Datetime serialization
  .gitignore
  connexion/apis/abstract.py
  connexion/apis/aiohttp_api.py
  connexion/apis/flask_api.py
  connexion/jsonifier.py
  connexion/utils.py
  examples/openapi3/helloworld_aiohttp/README.rst
  examples/openapi3/helloworld_aiohttp/hello.py
  examples/openapi3/helloworld_aiohttp/openapi/helloworld-api.yaml
  requirements-aiohttp.txt
  setup.py
  tests/aiohttp/test_aiohttp_api_secure.py
  tests/aiohttp/test_aiohttp_datetime.py
  tests/aiohttp/test_aiohttp_simple_api.py
  tests/conftest.py
  tests/fakeapi/aiohttp_handlers.py
  tests/fakeapi/hello.py
  tests/fixtures/aiohttp/datetime_support.yaml
  tests/fixtures/datetime_support/openapi.yaml
  tests/fixtures/datetime_support/swagger.yaml
  tests/test_flask_encoder.py
Labels: ready

#1084 Allow users to enable debug mode via environment variables
  connexion/apps/abstract.py
  tests/test_app.py
Labels: bugfix, ready

#1091 fixed mocks not honouring OpeanAPI 3 examples standard (printing "val…
  connexion/operations/openapi.py
  tests/test_mock3.py
Labels: bugfix, oas3, ready

#885 Forward options to the AioHTTP app.
  connexion/apps/aiohttp_app.py
Labels: aiohttp

#1010 Test schema corrections
  tests/fixtures/simple/openapi.yaml
Labels: ready

#823 Serve correct openapi spec basepath when path is altered by reverse-proxy
  connexion/apis/aiohttp_api.py
  connexion/apis/flask_api.py
  connexion/spec.py
  examples/openapi3/reverseproxy/README.rst
  examples/openapi3/reverseproxy/app.py
  examples/openapi3/reverseproxy/openapi.yaml
  examples/openapi3/reverseproxy_aiohttp/README.rst
  examples/openapi3/reverseproxy_aiohttp/app.py
  examples/openapi3/reverseproxy_aiohttp/nginx.conf
  examples/openapi3/reverseproxy_aiohttp/openapi.yaml
  setup.py
  tests/aiohttp/test_aiohttp_reverse_proxy.py
  tests/api/test_responses.py
  tests/conftest.py
Labels: feature, ready, swagger ui
