Repository zalando/connexion, pull requests merged in 2020-01, with the labels that each got.

#1075 enable empty security definition
  connexion/decorators/security.py
  connexion/operations/secure.py
  tests/api/test_secure_api.py
  tests/fakeapi/hello.py
  tests/fixtures/secure_endpoint/openapi.yaml
  tests/fixtures/secure_endpoint/swagger.yaml
Labels: waiting contributor feedback

#1125 Fixes Build: Allow new datetime behavior in PyYAML 5.3
  tests/aiohttp/test_aiohttp_datetime.py
  tests/test_flask_encoder.py
Labels: bugfix

#1122 x-nullable $ref fix
  .gitignore
  connexion/decorators/validation.py
  tests/decorators/test_validation.py
Labels: unsupported

#1110 scope deepObject defaults code to query params only
  connexion/decorators/uri_parsing.py
  connexion/operations/openapi.py
  connexion/utils.py
  tests/api/test_parameters.py
Labels: bugfix

#1124 Fixes #1020, OAS3 false positive for extra form param
  connexion/decorators/validation.py
  tests/api/test_parameters.py
Labels: bugfix

#1138 fix nested additionalProperties
  connexion/operations/openapi.py
  tests/api/test_responses.py
  tests/fakeapi/hello.py
  tests/fixtures/simple/openapi.yaml
Labels: bugfix
